<?php
$_localize = array(
    'home' => array('en' => 'Home', 'ar' => 'الرئيسية'),
    'sizetable' => array('en' => 'Sizetable', 'ar' => 'جدول المقاسات'),
    'explainer_video' => array('en' => 'Explainer Video', 'ar' => 'فيديو توضيحي'),
    'body_measurements' => array('en' => 'Take body measurements', 'ar' => 'طريقة اخذ مقاسات الجسم بالصور'),
    'sizetable_table' => array('en' => 'American specifications size table', 'ar' => 'جدول المقاسات بالمواصفات الامريكية'),
    'order' => array('en' => 'Order', 'ar' => 'طلب'),
    'new_order' => array('en' => 'New Order', 'ar' => 'طلب جديد'),
    'order_history' => array('en' => 'Order History', 'ar' => 'لائحة الطلبات'),
    'guid' => array('en' => 'Production steps', 'ar' => 'خطوات انتاج الزي'),
    'about_us' => array('en' => 'About Us', 'ar' => 'من نحن'),
    'login' => array('en' => 'Login', 'ar' => 'الدخول'),
    'logout' => array('en' => 'Logout', 'ar' => 'خروج'),
    'sizetable_heading' => array('en' => 'Size table according to American specifications', 'ar' => 'جدول المقاسات بالمواصفات الامريكية'),
    'body_measurements_heading' => array('en' => 'Take body measurements with pictures', 'ar' => 'طريقة اخذ قياسات الجسم ( الاطوال و الدورانات )'),
    'explainer_video_heading' => array('en' => 'Explainer video', 'ar' => 'فيديو يوضح طريقة اخذ قياسات التيشرت T-shirt'),
    'about_us_intro' => array('en' => 'An online store specializing in the design and production of the workers uniform, the use of technology and technological development witnessing this century in the field of computers, and the use of modern technologies, including their logic, and diamond, and supporting the extended reality use that exists in their mothers and mothers.', 'ar' => 'متجر الكتروني متخصص في تصميم وانتاج الزي الموحد للعامل ، واستخدام التطور التكنولوجي الذي يشهده هذا القرن في مجال الحاسب ، واستخدام التقنيات المتطورة لإثراء الاتجاهات العلمية منها والفنية ، ولما لها من فعاليات فائقة الدقة في اختزال الوقت وتقليل التكلفة الاقتصادية لإرضاء احتياجات المستهلك ، فاتجهت الباحثة الى استخدام تقنية الواقع الممتد Extended Realit في انتاج العينة الأولى للزي الموحد في محاولة منها لتطوير دعائم المنتج الملبسي .'),
    'guid_heading' => array('en' => 'Table stages for production of overall', 'ar' => 'جدول مراحل انتاج الأفرول'),
    'name' => array('en' => 'Name', 'ar' => 'اسم'),
    'company' => array('en' => 'Company', 'ar' => 'شركة'),
    'register' => array('en' => 'Register', 'ar' => 'يسجل'),
    'phone' => array('en' => 'Phone', 'ar' => 'هاتف'),
    'address' => array('en' => 'Address', 'ar' => 'عنوان'),
    'password' => array('en' => 'Password', 'ar' => 'كلمة المرور '),
    'email' => array('en' => 'Email', 'ar' => 'البريد الإلكتروني '),
    'already_have_account' => array('en' => 'Already have an account <u> Login</u>', 'ar' => 'لديك حساب بالفعل <u>تسجيل الدخول</u>'),
    'dont_have_account' => array('en' => 'Dont have account!', 'ar' => 'اضغط هنا للتسجيل'),
    'a' => array('en' => '', 'ar' => ''),
    'a' => array('en' => '', 'ar' => ''),
    'a' => array('en' => '', 'ar' => ''),
    'templates' => array('en' => 'Templates', 'ar' => 'النماذج'),
    'introduction_title' => array('en' => 'Introduction', 'ar' => 'المقدمة'),
    'our_vision_title' => array('en' => 'Our Vision', 'ar' => 'الرؤية'),
    'objectives_title' => array('en' => 'Objectives', 'ar' => 'الهدف'),
    'introduction' => array('en' => 'The sample in the ready-made garment industry is the actual reflectance t of the designer’s idea, which shows the validity of the design for mass production with different sizes. The sample process is most important in the apparel production because it predicts the quality of the product and determines the processes during production, as accessories, costs of the apparel, consumption time, to produce the order based on the capacity of the factory.
    The development in interactive technology has led to new forms of interaction that are close to real, the virtual reality presentations and interactive experiences generated by computer, it allows the user to have a virtual tour in a virtual environment that is close to reality, and may even be better than it. They allowed exchanging images that are close to reality, and interact with them with audio and video, so it can see what cannot be seen in Indeed.
    Extended Reality refers to both real and virtual environments, and to the interaction between humans and elements that generated by computer. Extended reality is also an umbrella for augmented reality, virtual reality, and mixed reality, as it includes all of them under one name, which is extended reality.
    ', 'ar' => '
    العينة في صناعة الملابس الجاهزة هي الترجمة الفعلية لفكرة المصمم التي توضح مدى صلاحية التصميم للتنفيذ بكميات كبيرة وبمقاسات متعددة ، فمرحلة عمل العينة تعد من اهم مراحل انتاج الملابس لأنها تتنبأ بجودة المنتج وتحدد العمليات التي يمر بها اثناء الإنتاج ومستلزمات وتكاليف الإنتاج وتكلفة القطعة للمستهلك والوقت المستغرق لإنهاء الطلبية بناء على إمكانيات المصنع المتاحة.
وقد أدى التطور في التكنولوجيا التفاعلية إلى وجود صيغ جديدة للتفاعل قريبة من الواقعية. واستخدم عروض الواقع الافتراضي والخبرات التفاعلية المولدة بالكمبيوتر، يسمح للمستخدم بأخذ جولة افتراضية في بيئة افتراضية قريبة من الواقع، بل قد تكون أفضل منه، حيث يتاح لهم تداول الصور القريبة من الواقع، ويتفاعلون معها، بالصوت والصورة، فيرى مالا يمكن رؤيته في الواقع.   
وتشير تقنية الواقع الممتد ( Extended Realit ) إلى البيئات الحقيقية ، والافتراضية معاً، وإلى التفاعل بين الإنسان والعناصر التي تم إنشاؤها بواسطة الحاسوب؛ كما يعد الواقع الممتد مظلة لكل من الواقع المعزز، والواقع الافتراضي، والواقع المدمج، فهو يشملها جميعها تحت اسم واحد وهو الواقع الممتد.
    '),
    'our_vision' => array('en' => 'Our vision is to enhance and develop and to interact between scientific research with high technology, to try, develop and improve the production efficiency of the clothing and textile sector in the Kingdom of Saudi Arabia according to the Kingdom’s vision 2030 (assorted economy), and to cooperate between academic bodies and the ready-made garment sector.', 'ar' => 'تعزيز و مواكبة العالم الحديث والتفاعل بين الأبحاث العلمية مع ما يسمى بعصر التكنولوجيا و الحواسب ، محاولة تطوير وتحسين الكفاءة الإنتاجية لقطاع الملابس والنسيج بالمملكة العربية السعودية تماشياً مع رؤية المملكة 2030( اقتصاد مزدهر ) ، الربط بين الجهات الأكاديمية و قطاع صناعة الملابس الجاهزة .'),
    'our_mission' => array('en' => '1. Determine the technical requirements for the production of the pre sample of workers uniform (Overalls) in the ready-made garment industry <br />
    2. Design a database for the vocabulary of the pre sample of workers uniform (Overalls) using Extended Reality technology <br />
    3. Measure the effect of extended reality technology in the production of the pre sample of workers uniforms (Overalls) to reduce the time and cost and improve the quality of the samples..
    About us
    We are an online store for design and production the workers uniforms by using new and advanced technology to support the scientific and technical trends and to reduce time and costs of apparel production to satisfy consumer requirements.
    The researcher used the Extended Reality technology to produce the pre sample of the uniform to develop the main product of apparel.', 'ar' => '
    -	تحديد المتطلبات التقنية لإنتاج العينة الأولى لملابس العمال ( الأفرول ) في صناعة الملابس الجاهزة <br>
-	تصميم قاعدة بيانات لمفردات العينة الأولى لملابس العمال ( الأفرول ) باستخدام تقنية الواقع الممتد  (Extended Realit) <br>-	قياس أثر استخدام تقنية الواقع الممتد )  ( Extended Realit في انتاج العينة الأولى ملابس العمال ( الأفرول ) على خفض زمن و تكلفة و رفع جودة العينات المنتجة .')
);